### PR TITLE
Update mocha-jsdom versioning

### PR DESCRIPTION
**Pull request by kwebster2**
@cernanb 
Fixes common mocha-jsdom version issue

### CODE REVIEW

**Comment by kwebster2** [comment]
@fi-curriculum-team 
Hey team, this is an outstanding issue on all JS labs using mocha-jsdom. Bootcamp Prep students cannot complete any of these labs without having to be told to modify their package.json file in AAQ. Could we merge this and the other PRs? 

Thanks!

**Comment by kwebster2** [comment]
@DanielSeehausen FYI ^

**Comment by DanielSeehausen** [comment]
@kwebster2 @maxwellbenton @sgharms is this still the case? passing this off to the A-team and unsubscribing.

**Comment by maxwellbenton** [comment]
Thank you for submitting this PR and catching this issue.

We've merged the pull request in and have been making this update to package.json files throughout our courses. Thank you for contributing to a learn-co-curriculum repository and helping future students learn to code!

We appreciate your support!

**Pull request merged**
